spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user1
    password: password
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
