version: '3'

services:

  db_postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
